name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
ğŸš€

Criando seu primeiro fluxo de trabalho 2

on: [push]
jobs:
Explore-GitHub-Actions:
runs-on: ubuntu-latest
steps:
- run: echo "ğŸ‰ The job was automatically triggered b
y a ${{ github.event_name }} event."
- run: echo "ğŸ§ This job is now running on a ${{ runn
er.os }} server hosted by GitHub!"
- run: echo "ğŸ” The name of your branch is ${{ githu
b.ref }} and your repository is ${{ github.repository }}."
- name: Check out repository code
uses: actions/checkout@v4
- run: echo "ğŸ’¡ The ${{ github.repository }} reposito
ry has been cloned to the runner."
- run: echo "ğŸ–¥ The workflow is now ready to test you
r code on the runner."
- name: List files in the repository
run: |
ls ${{ github.workspace }}
- run: echo "ğŸ This job's status is ${{ job.status
}}."
